## My First Dataframe

In [15]:
import pandas as pd
import numpy as np

In [16]:
# creating data
movies_data = {
    "Title": [
        "Inception", "Interstellar", "The Dark Knight", "Avengers: Endgame",
        "Parasite", "Joker", "Titanic", "3 Idiots",
        "The Matrix", "Spider-Man: No Way Home"
    ],
    
    "Year": [
        2010, 2014, 2008, 2019,
        2019, 2019, 1997, 2009,
        1999, 2021
    ],
    
    "Rating": [
        8.8, 8.6, 9.0, 8.4,
        8.5, 8.4, 7.9, 8.4,
        8.7, 8.2
    ],
    
    "Genre": [
        "Sci-Fi", "Sci-Fi", "Action", "Action",
        "Thriller", "Drama", "Romance", "Comedy",
        "Sci-Fi", "Action"
    ]
}

In [17]:
#creating dataframes

df_movie=pd.DataFrame(movies_data)

In [18]:
df_movie

                     Title  Year  Rating     Genre
0                Inception  2010     8.8    Sci-Fi
1             Interstellar  2014     8.6    Sci-Fi
2          The Dark Knight  2008     9.0    Action
3        Avengers: Endgame  2019     8.4    Action
4                 Parasite  2019     8.5  Thriller
5                    Joker  2019     8.4     Drama
6                  Titanic  1997     7.9   Romance
7                 3 Idiots  2009     8.4    Comedy
8               The Matrix  1999     8.7    Sci-Fi
9  Spider-Man: No Way Home  2021     8.2    Action

In [19]:
df_movie.describe()

              Year     Rating
count    10.000000  10.000000
mean   2011.500000   8.490000
std       8.514693   0.310734
min    1997.000000   7.900000
25%    2008.250000   8.400000
50%    2012.000000   8.450000
75%    2019.000000   8.675000
max    2021.000000   9.000000

In [20]:
##to save file as csv

df_movie.to_csv('miniproject.ipynb')

In [23]:
df=pd.Series(movies_data)
df

Title     [Inception, Interstellar, The Dark Knight, Ave...
Year      [2010, 2014, 2008, 2019, 2019, 2019, 1997, 200...
Rating    [8.8, 8.6, 9.0, 8.4, 8.5, 8.4, 7.9, 8.4, 8.7, ...
Genre     [Sci-Fi, Sci-Fi, Action, Action, Thriller, Dra...
dtype: object

In [25]:
df_movie=df_movie.head()
df_movie

               Title  Year  Rating     Genre
0          Inception  2010     8.8    Sci-Fi
1       Interstellar  2014     8.6    Sci-Fi
2    The Dark Knight  2008     9.0    Action
3  Avengers: Endgame  2019     8.4    Action
4           Parasite  2019     8.5  Thriller

In [27]:
df_movie=df_movie.tail(3)
df_movie

               Title  Year  Rating     Genre
2    The Dark Knight  2008     9.0    Action
3  Avengers: Endgame  2019     8.4    Action
4           Parasite  2019     8.5  Thriller